services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        SeoAnalyser\Checker\CheckerInterface:
            tags: ['seo_analyser_checker']
        SeoAnalyser\Format\FormatterInterface:
            tags: ['seo_analyser_formatter']

    SeoAnalyser\:
        resource: '../src'
        exclude: '../src/Resource/'
  
    GuzzleHttp\Client: ~

    JMS\Serializer\SerializerBuilder:
        factory: ['JMS\Serializer\SerializerBuilder', 'create']

    Twig\Loader\FilesystemLoader:
        $paths: "%bin_path%/../src/Resources/views"

    Twig\Environment:
        $loader: '@Twig\Loader\FilesystemLoader'
        calls:
            - [addExtension, ['@SeoAnalyser\Twig\SanitiseExtension']]
            - [addExtension, ['@SeoAnalyser\Twig\SeverityExtension']]
            - [addExtension, ['@SeoAnalyser\Twig\VersionExtension']]
        