services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        SeoAnalyser\Checker\CheckerInterface:
            tags: ['seo_analyser_checker']
        SeoAnalyser\Format\FormatterInterface:
            tags: ['seo_analyser_formatter']

    SeoAnalyser\:
        resource: '../src'
        exclude: '../src/Sitemap'
  
    GuzzleHttp\Client: ~